drop table if exists comments;
drop table if exists bookings;
Drop Table if exists items;
DROP TABLE IF EXISTS users;


CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
    );

create table IF NOT EXISTS items
(
    id          serial
        constraint items_pk
            primary key
        unique,
    name        varchar,
    description varchar not null,
    available   boolean not null,
    owner       integer
        constraint items_users_id_fk
            references users
);

create table if not exists bookings
(
    id         serial
        constraint bookings_pk
            primary key
        unique,
    item_id    integer not null
        constraint bookings_items_id_fk
            references items,
    start_date timestamp,
    end_date   timestamp,
    booker_id  integer
        constraint bookings_users_id_fk
            references users,
    status     varchar
);

create table if not exists comments
(
    id        serial
        constraint comments_pk
            primary key
        unique,
    text      varchar,
    item_id   integer
        constraint comments_items_id_fk
            references items,
    author_id integer
        constraint comments_users_id_fk
            references users,
    created   timestamp
);